module.exports = {
  projects: [
    '<rootDir>/apps/be-todos',
    '<rootDir>/libs/utils',
    '<rootDir>/libs/types',
    '<rootDir>/libs/be-api-base',
    '<rootDir>/libs/be-todos',
    '<rootDir>/libs/be-todos-lib',
    '<rootDir>/apps/chances',
    '<rootDir>/libs/chances-lib',
    '<rootDir>/libs/loteria-lib',
    '<rootDir>/apps/loteria',
    '<rootDir>/libs/lotto-lib',
    '<rootDir>/apps/lotto',
    '<rootDir>/libs/monazos-lib',
    '<rootDir>/apps/monazos',
    '<rootDir>/libs/tiempos-lib',
    '<rootDir>/apps/tiempos',
    '<rootDir>/libs/product-resource-lib',
    '<rootDir>/apps/product-resource',
    '<rootDir>/apps/monolithic',
  ],
};
